import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import { contentConfig, logicalResolution, pixelPerfectOptions, getRenderingPolicy } from '../src/content/babylon/config.js';
import { getInitializationMessage } from '../src/content/babylon/initialization.js';
import { getLogicalToRenderScale } from '../src/content/babylon/pixel-perfect.js';
import { cycleRenderResolutionPreset, getRenderResolutionDimensions } from '../src/content/babylon/render-resolution.js';

test('uses Babylon Lite WebGPU and crisp pixel-perfect sampling for the 320x576 playfield',()=>{assert.deepEqual(contentConfig,{renderer:'babylon-lite',style:'2d'});assert.deepEqual(logicalResolution,{width:320,height:576});assert.equal(getRenderingPolicy(contentConfig),'pixel-perfect');assert.deepEqual(pixelPerfectOptions.engine,{msaaSamples:1,alphaMode:"premultiplied"});assert.equal(pixelPerfectOptions.texture.minFilter,'nearest');assert.equal(pixelPerfectOptions.texture.magFilter,'nearest');assert.equal(pixelPerfectOptions.texture.mipMaps,false);assert.equal(getLogicalToRenderScale(640,1152,logicalResolution),2);});
test('resolves all render presets as integer dimensions derived from the native backing',()=>{assert.deepEqual(getRenderResolutionDimensions(640,1152,'quarter'),{preset:'quarter',width:160,height:288,scale:.25});assert.deepEqual(getRenderResolutionDimensions(640,1152,'half'),{preset:'half',width:320,height:576,scale:.5});assert.deepEqual(getRenderResolutionDimensions(640,1152,'native'),{preset:'native',width:640,height:1152,scale:1});assert.deepEqual(getRenderResolutionDimensions(640,1152,'double'),{preset:'double',width:1280,height:2304,scale:2});assert.deepEqual(getRenderResolutionDimensions(321,577,'half'),{preset:'half',width:160,height:288,scale:Math.min(160/321,288/577)});assert.equal(cycleRenderResolutionPreset('double'),'quarter');assert.equal(cycleRenderResolutionPreset('invalid'),'double');assert.deepEqual(getRenderResolutionDimensions(0,10,'double'),{preset:'double',width:0,height:0,scale:0});});
test('caps double-resolution targets to WebGPU texture limits while retaining aspect',()=>{const capped=getRenderResolutionDimensions(640,1152,'double',1536);assert.deepEqual(capped,{preset:'double',width:853,height:1536,scale:Math.min(853/640,1536/1152)});assert.ok(capped.width<=1536&&capped.height<=1536);assert.ok(Math.abs(capped.width/capped.height-640/1152)<.001);const boundary=getRenderResolutionDimensions(640,1152,'double',2304);assert.deepEqual(boundary,{preset:'double',width:1280,height:2304,scale:2});});
test('produces a clear WebGPU recovery message',()=>{assert.match(getInitializationMessage(false,new Error('unsupported')),/requires WebGPU/);assert.match(getInitializationMessage(true,new Error('texture decode failed')),/could not initialize/);});
test('loads generated background and original crisp game sprite atlas',async()=>{const atlas=await readFile(new URL('../src/content/babylon/images/neon-brick-atlas.png',import.meta.url));const png=await readFile(new URL('../documentation/neon-space-background.png',import.meta.url));assert.deepEqual([...atlas.subarray(0,8)],[137,80,78,71,13,10,26,10]);assert.deepEqual([...png.subarray(0,8)],[137,80,78,71,13,10,26,10]);});
test('cleans renderer resources and continues rendering current server snapshots',async()=>{const content=await readFile(new URL('../src/content/Content.jsx',import.meta.url),'utf8');for(const re of [/cancelled=true/ ,/resizeObserver\?\.disconnect\(\)/,/disposeSpriteRenderer\(renderer\)/,/releaseTexture\(texture\)/,/disposeEngine\(engine\)/,/paintRef\.current=paint/,/centerSprite2DView\(layer\.view,logicalResolution\.width\/2,logicalResolution\.height\/2/])assert.match(content,re);});
test('renders selected target sizes with nearest sampling and reports resize allocation failures',async()=>{const content=await readFile(new URL('../src/content/Content.jsx',import.meta.url),'utf8');assert.match(content,/createRenderTexture2D\(engine,resolved\.width,resolved\.height,\{[^}]*minFilter:'nearest',magFilter:'nearest'/);assert.match(content,/setSpriteRendererTarget\(renderer,renderTexture\)/);assert.match(content,/setSpriteRendererTarget\(renderer,null\)/);assert.match(content,/catch\(error\)\{failInitialization\(error\);\}/);});



