import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import { movePaddleInput, toPaddleInput } from '../src/game/controls.js';
import { advancePaddleTowardTarget, getRemotePaddleInterpolationDelay, getRemotePaddleSampleTime, paddleTargetX, pushGameSnapshot, samplePaddlePositions, smoothRemotePaddlePosition } from '../src/game/presentation.js';

test('maps pointer positions across the full stage for either player',()=>{assert.equal(toPaddleInput(0),0);assert.equal(toPaddleInput(.25),.25);assert.equal(toPaddleInput(.75),.75);assert.equal(toPaddleInput(1),1);assert.equal(toPaddleInput(NaN),.5);assert.equal(paddleTargetX(0),19);assert.equal(paddleTargetX(1),301);assert.equal(paddleTargetX(.5),160);assert.equal(paddleTargetX(0,54),27);assert.equal(paddleTargetX(1,54),293);});
test('keyboard input moves across the same full width for either player',()=>{assert.equal(movePaddleInput(.02,-1),0);assert.equal(movePaddleInput(.98,1),1);assert.equal(movePaddleInput(.5,1),.545);});
test('remote paddle snapshots interpolate smoothly and briefly extrapolate through jitter',()=>{const history=[];pushGameSnapshot(history,{paddles:[{seat:0,x:50,target:90,width:38},{seat:1,x:210,target:250,width:38}]},100);pushGameSnapshot(history,{paddles:[{seat:0,x:70,target:90,width:54},{seat:1,x:230,target:250,width:54}]},150);const middle=samplePaddlePositions(history,125);assert.equal(middle[0].x,60);assert.equal(middle[0].width,46);assert.equal(middle[1].x,220);assert.equal(samplePaddlePositions(history,50)[0].x,50);assert.equal(samplePaddlePositions(history,175)[1].x,236.5);assert.equal(samplePaddlePositions(history,250)[1].x,243);});
test('server epoch timestamps map onto the client monotonic playback clock',()=>{const history=[];pushGameSnapshot(history,{serverTime:1_800_000_000_000,paddles:[{seat:0,x:50,target:90,width:38}]},10_000);pushGameSnapshot(history,{serverTime:1_800_000_000_050,paddles:[{seat:0,x:70,target:90,width:38}]},10_050);assert.equal(history[0].timelineAt,10_000);assert.equal(history[1].timelineAt,10_050);const sampleAt=getRemotePaddleSampleTime(history,10_100,75);assert.equal(sampleAt,10_025);assert.equal(samplePaddlePositions(history,sampleAt)[0].x,60);});
test('remote paddle playback keeps one steady buffer when packet arrival jitter changes',()=>{const history=[];for(const receivedAt of [100,150,207,408,451,502]){pushGameSnapshot(history,{paddles:[{seat:0,x:receivedAt/10,target:100,width:38}]},receivedAt,32);assert.equal(getRemotePaddleInterpolationDelay(history),250);}});
test('remote playback clock does not jump when a delayed packet arrives',()=>{const history=[];pushGameSnapshot(history,{serverTime:1000,paddles:[{seat:0,x:10,width:38}]},1000);const before=getRemotePaddleSampleTime(history,1150);pushGameSnapshot(history,{serverTime:1050,paddles:[{seat:0,x:20,width:38}]},1220);const after=getRemotePaddleSampleTime(history,1220);assert.equal(before,900);assert.equal(after,970);assert.equal(after-before,70);});
test('local paddle prediction follows the server speed and full-width position',()=>{assert.equal(paddleTargetX(0),19);assert.equal(paddleTargetX(1),301);assert.equal(advancePaddleTowardTarget(160,301,.05),173);assert.equal(advancePaddleTowardTarget(160,301,.1),173);});
test('remote render smoothing is frame-rate independent and converges without changing the target',()=>{const oneFrame=smoothRemotePaddlePosition(100,200,1/60);const twoHalfFrames=smoothRemotePaddlePosition(smoothRemotePaddlePosition(100,200,1/120),200,1/120);assert.ok(Math.abs(oneFrame-twoHalfFrames)<1e-9);assert.ok(oneFrame>100&&oneFrame<200);assert.equal(smoothRemotePaddlePosition(100,200,0),100);});
test('focus, local pause and teardown release input without duplicate StrictMode room joins',async()=>{const [content,session]=await Promise.all([readFile(new URL('../src/content/Content.jsx',import.meta.url),'utf8'),readFile(new URL('../src/game/GameSession.jsx',import.meta.url),'utf8')]);assert.match(content,/window\.addEventListener\('blur',blur\)/);assert.match(content,/if\(paused\)send\('input',\{x:\.5\}\)/);assert.match(content,/samplePaddlePositions/);assert.match(content,/advancePaddleTowardTarget/);assert.match(content,/setInterval\(\(\)=>send\('input'/);assert.match(session,/client\.disconnect\(\)/);assert.match(session,/client\.send\('input',\{x:\.5\}\)/);assert.match(session,/const connectTimer=window\.setTimeout\(\(\)=>\{if\(active\)void client\.connect\(\);\},0\)/);assert.match(session,/window\.clearTimeout\(connectTimer\)/);});
