import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import { moveLaneInput, toLaneInput } from '../src/game/controls.js';
import { advancePaddleTowardTarget, laneTargetX, pushGameSnapshot, samplePaddlePositions } from '../src/game/presentation.js';

test('maps pointer targets into each player’s lane and clamps invalid input',()=>{assert.equal(toLaneInput(.25,0),.5);assert.equal(toLaneInput(.75,1),.5);assert.equal(toLaneInput(0,1),0);assert.equal(toLaneInput(1,0),1);assert.equal(toLaneInput(NaN,0),.5);});
test('keyboard input remains inside its assigned lane',()=>{assert.equal(moveLaneInput(.02,-1),0);assert.equal(moveLaneInput(.98,1),1);assert.equal(moveLaneInput(.5,1),.545);});
test('remote paddle snapshots interpolate smoothly and briefly extrapolate through jitter',()=>{const history=[];pushGameSnapshot(history,{paddles:[{seat:0,x:50,target:90,width:38},{seat:1,x:210,target:250,width:38}]},100);pushGameSnapshot(history,{paddles:[{seat:0,x:70,target:90,width:54},{seat:1,x:230,target:250,width:54}]},150);const middle=samplePaddlePositions(history,125);assert.equal(middle[0].x,60);assert.equal(middle[0].width,46);assert.equal(middle[1].x,220);assert.equal(samplePaddlePositions(history,50)[0].x,50);assert.equal(samplePaddlePositions(history,175)[1].x,236.5);assert.equal(samplePaddlePositions(history,250)[1].x,243);});
test('local paddle prediction follows server speed and maps both seat lanes',()=>{assert.equal(laneTargetX(0,0),20);assert.equal(laneTargetX(0,1),140);assert.equal(laneTargetX(1,0),180);assert.equal(laneTargetX(1,1),300);assert.equal(advancePaddleTowardTarget(80,140,.05),93);assert.equal(advancePaddleTowardTarget(80,140,.1),93);});
test('focus, local pause and teardown release local paddle input',async()=>{const [content,session]=await Promise.all([readFile(new URL('../src/content/Content.jsx',import.meta.url),'utf8'),readFile(new URL('../src/game/GameSession.jsx',import.meta.url),'utf8')]);assert.match(content,/window\.addEventListener\('blur',blur\)/);assert.match(content,/if\(paused\)send\('input',\{x:\.5\}\)/);assert.match(content,/samplePaddlePositions/);assert.match(content,/advancePaddleTowardTarget/);assert.match(content,/setInterval\(\(\)=>send\('input'/);assert.match(session,/client\.disconnect\(\)/);assert.match(session,/client\.send\('input',\{x:\.5\}\)/);});
