import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import { movePaddleInput, toPaddleInput } from '../src/game/controls.js';
import { advancePaddleTowardTarget, paddleTargetX, pushGameSnapshot, samplePaddlePositions } from '../src/game/presentation.js';

test('maps pointer positions across the full stage for either player',()=>{assert.equal(toPaddleInput(0),0);assert.equal(toPaddleInput(.25),.25);assert.equal(toPaddleInput(.75),.75);assert.equal(toPaddleInput(1),1);assert.equal(toPaddleInput(NaN),.5);assert.equal(paddleTargetX(0),19);assert.equal(paddleTargetX(1),301);assert.equal(paddleTargetX(.5),160);assert.equal(paddleTargetX(0,54),27);assert.equal(paddleTargetX(1,54),293);});
test('keyboard input moves across the same full width for either player',()=>{assert.equal(movePaddleInput(.02,-1),0);assert.equal(movePaddleInput(.98,1),1);assert.equal(movePaddleInput(.5,1),.545);});
test('remote paddle snapshots interpolate smoothly and briefly extrapolate through jitter',()=>{const history=[];pushGameSnapshot(history,{paddles:[{seat:0,x:50,target:90,width:38},{seat:1,x:210,target:250,width:38}]},100);pushGameSnapshot(history,{paddles:[{seat:0,x:70,target:90,width:54},{seat:1,x:230,target:250,width:54}]},150);const middle=samplePaddlePositions(history,125);assert.equal(middle[0].x,60);assert.equal(middle[0].width,46);assert.equal(middle[1].x,220);assert.equal(samplePaddlePositions(history,50)[0].x,50);assert.equal(samplePaddlePositions(history,175)[1].x,236.5);assert.equal(samplePaddlePositions(history,250)[1].x,243);});
test('local paddle prediction follows the server speed and full-width position',()=>{assert.equal(paddleTargetX(0),19);assert.equal(paddleTargetX(1),301);assert.equal(advancePaddleTowardTarget(160,301,.05),173);assert.equal(advancePaddleTowardTarget(160,301,.1),173);});
test('focus, local pause and teardown release input without duplicate StrictMode room joins',async()=>{const [content,session]=await Promise.all([readFile(new URL('../src/content/Content.jsx',import.meta.url),'utf8'),readFile(new URL('../src/game/GameSession.jsx',import.meta.url),'utf8')]);assert.match(content,/window\.addEventListener\('blur',blur\)/);assert.match(content,/if\(paused\)send\('input',\{x:\.5\}\)/);assert.match(content,/samplePaddlePositions/);assert.match(content,/advancePaddleTowardTarget/);assert.match(content,/setInterval\(\(\)=>send\('input'/);assert.match(session,/client\.disconnect\(\)/);assert.match(session,/client\.send\('input',\{x:\.5\}\)/);assert.match(session,/const connectTimer=window\.setTimeout\(\(\)=>\{if\(active\)void client\.connect\(\);\},0\)/);assert.match(session,/window\.clearTimeout\(connectTimer\)/);});
