import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import viteConfig from '../../vite.config.js';
import { defaultLayout, fitViewport, validateLayout } from '../src/ui/layout.js';
import { configStorageKey, defaultConfig, fullscreenStorageKey, persistConfig, readConfig } from '../src/ui/settings.js';

test('keeps the npm project at root and serves the named game under its Pages base',async()=>{assert.equal(viteConfig.root,'neon-breaker-duo');assert.equal(viteConfig.base,'/babylon-lite-arkanoid-clone/');const pages=await readFile(new URL('../../.github/workflows/deploy-pages.yml',import.meta.url),'utf8');assert.match(pages,/cp -R neon-breaker-duo\/dist\/. _site\//);});
test('uses a portrait default and fits it to desktop and narrow screens',()=>{assert.equal(defaultLayout.orientation,'portrait');for(const [w,h] of [[1600,900],[390,844],[320,576],[160,100]]){const fit=fitViewport(w,h,defaultLayout);assert.ok(fit.width<=w&&fit.height<=h);assert.ok(Math.abs(fit.width/fit.height-9/16)<1e-8);}});
test('fixes the game to its portrait layout with no orientation chooser',async()=>{const app=await readFile(new URL('../src/ui/App.jsx',import.meta.url),'utf8');assert.match(app,/const activeLayout = layout/);assert.match(app,/key === "o"\) setActiveDialog/);assert.doesNotMatch(app,/aspectRatioPresets|orientationOverride|Portrait|Landscape/);});
test('retains all four compact template corner roles and useful game controls',async()=>{const [app,content,main,html,readme]=await Promise.all(['src/ui/App.jsx','src/content/Content.jsx','src/main.jsx','index.html','../README.md'].map(f=>readFile(new URL('../'+f,import.meta.url),'utf8')));for(const corner of ['top_left','top_right','bottom_left','bottom_right'])assert.ok(app.includes(`position="${corner}"`));assert.match(app,/NEON BREAKER DUO/);assert.match(app,/noopener noreferrer/);assert.match(app,/SETTINGS/);assert.match(content,/LAUNCH/);assert.match(content,/PAUSE/);assert.match(content,/state\.status==='full'/);assert.match(content,/outcome==='victory'/);assert.match(content,/outcome==='defeat'/);assert.match(main,/GameSessionProvider/);assert.match(html,/Neon Breaker Duo/);assert.match(readme,/Original AI Prompt/);});
test('provides a visible accessible resolution button and mirrors it in Babylon settings',async()=>{const app=await readFile(new URL('../src/ui/App.jsx',import.meta.url),'utf8');assert.match(app,/id="render_resolution"/);assert.match(app,/onClick=\{cycleRenderPreset\}/);assert.match(app,/aria-label=\{renderResolutionText\}/);assert.match(app,/key === "r" && !event.repeat/);assert.match(app,/Babylon Lite<\/div><button[^>]*\{renderResolutionText\}/);});
test('persists render resolution and preserves existing settings defaults and fullscreen key',()=>{const values=new Map();const storage={getItem:(key)=>values.get(key)??null,setItem:(key,value)=>values.set(key,String(value))};assert.deepEqual(readConfig(storage),defaultConfig);values.set(fullscreenStorageKey,'true');assert.equal(readConfig(storage).fullscreen,true);const saved={fullscreen:false,hudVisible:false,renderPreset:'quarter'};assert.equal(persistConfig(saved,storage),true);assert.deepEqual(readConfig(storage),saved);values.set(configStorageKey,JSON.stringify({...saved,renderPreset:'invalid'}));assert.equal(readConfig(storage).renderPreset,'native');const broken={getItem(){throw Error('unavailable')},setItem(){throw Error('unavailable')}};assert.deepEqual(readConfig(broken),defaultConfig);assert.equal(persistConfig(saved,broken),false);});
test('renders actual snapshots with Babylon Lite sprites and interpolation',async()=>{const [content,config]=await Promise.all([readFile(new URL('../src/content/Content.jsx',import.meta.url),'utf8'),readFile(new URL('../src/content/babylon/config.js',import.meta.url),'utf8')]);assert.match(config,/width: 320, height: 576/);for(const method of ['createEngine','createGridSpriteAtlas','createSprite2DLayer','createSpriteRenderer','updateSprite2D'])assert.ok(content.includes(method));assert.match(content,/getLogicalToRenderScale/);assert.match(content,/snapshotAtRef/);assert.match(content,/requestAnimationFrame/);assert.match(config,/minFilter: "nearest"/);assert.match(config,/mipMaps: false/);});
test('pins the verified compatible client release and gives safe local/prod endpoints',async()=>{const pkg=JSON.parse(await readFile(new URL('../../package.json',import.meta.url),'utf8'));const provider=await readFile(new URL('../src/game/GameSession.jsx',import.meta.url),'utf8');assert.match(pkg.dependencies['@rmc/multiplayer-client'],/v0\.9\.6\/rmc-multiplayer-client-0\.9\.6\.tgz/);assert.match(provider,/VITE_MULTIPLAYER_URL/);assert.match(provider,/http:\/\/127\.0\.0\.1:2567/);assert.match(provider,/https:\/\/rmc-colyseus-multiplayer-server\.vercel\.app/);});

